version: '3'

volumes:
  pg_data:
  static:
  media:

networks:
  app:

services:
  postgres:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app
  
  backend:
    image: jene4kabezdar/kittygram_backend:latest
    env_file: .env
    volumes:
      - media:/media
      - static:/backend_static
    depends_on:
      - postgres
    networks:
      - app

  frontend:
    image: jene4kabezdar/kittygram_frontend:latest
    volumes:
      - static:/app/build
    networks:
      - app

  nginx:
    image: jene4kabezdar/kittygram_gateway:latest
    ports:
      - "80:80"
    volumes:
      - media:/media
      - static:/static
    networks:
      - app
