version: '3'

volumes:
  pg_data:
  static:
  media:

networks:
  app:

services:
  postgres:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app
  
  backend:
    build: ./backend/
    env_file: .env
    volumes:
      - media:/media
      - static:/backend_static
    depends_on:
      - postgres
    networks:
      - app

  frontend:
    build: ./frontend/
    volumes:
      - static:/app/build
    networks:
      - app

  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    volumes:
      - media:/media
      - static:/static
    networks:
      - app
